"""
AI Response Store.

Shared helper for all reasoning nodes to persist actual AI Incident Commander
responses to the `ai_responses` table and broadcast them via WebSocket.

Usage:
    from app.reasoning.ai_response_store import store_ai_response

    store_ai_response(
        meeting_id=meeting_id,
        response_text="Database saturation is an unlikely primary cause...",
        response_type="analysis",
        trigger="fact_extracted",
        related_fact_ids=["uuid1", "uuid2"],
        confidence=0.85,
    )
"""

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import create_engine, text

from app.config.settings import settings

logger = logging.getLogger(__name__)


def store_ai_response(
    meeting_id: str,
    response_text: str,
    response_type: str = "analysis",
    trigger: str | None = None,
    related_fact_ids: list[str] | None = None,
    related_assumption_ids: list[str] | None = None,
    related_action_ids: list[str] | None = None,
    confidence: float | None = None,
    approval_status: str = "none",
    approval_id: str | None = None,
    execution_status: str = "none",
    jira_ticket_ref: str | None = None,
) -> dict[str, Any] | None:
    """
    Persists an AI Incident Commander response to the `ai_responses` table.

    Args:
        meeting_id: UUID of the current meeting.
        response_text: The actual text generated by the AI.
        response_type: One of: analysis | recommendation | summary | alert
        trigger: What triggered this response (e.g. "fact_extracted").
        related_fact_ids: List of fact UUIDs that informed this response.
        related_assumption_ids: List of assumption/hypothesis UUIDs.
        related_action_ids: List of action item UUIDs.
        confidence: Float 0.0–1.0 confidence score.
        approval_status: none | pending | approved | rejected
        approval_id: UUID of linked pending_approval if applicable.
        execution_status: none | executing | done | failed
        jira_ticket_ref: Jira issue key if executed (e.g. "INC-123").

    Returns:
        Dict representation of the stored record, or None on failure.
    """
    if not meeting_id or not response_text:
        return None

    raw_url = settings.database_url or os.environ.get("DATABASE_URL", "")
    if not raw_url:
        logger.warning("[AI RESPONSE STORE] DATABASE_URL not set — response not persisted")
        return None

    sync_url = raw_url.replace("postgresql+asyncpg://", "postgresql+psycopg2://")
    engine = create_engine(sync_url, pool_pre_ping=True)

    response_id = uuid.uuid4()
    now_utc = datetime.now(timezone.utc)

    try:
        meeting_uuid = uuid.UUID(meeting_id)

        with engine.connect() as conn:
            insert_sql = text("""
                INSERT INTO ai_responses (
                    id, meeting_id, response_text, response_type, trigger,
                    related_fact_ids, related_assumption_ids, related_action_ids,
                    approval_status, approval_id, execution_status,
                    jira_ticket_ref, confidence, created_at
                ) VALUES (
                    :id, :meeting_id, :response_text, :response_type, :trigger,
                    :related_fact_ids, :related_assumption_ids, :related_action_ids,
                    :approval_status, :approval_id, :execution_status,
                    :jira_ticket_ref, :confidence, :created_at
                )
            """)
            conn.execute(
                insert_sql,
                {
                    "id": response_id,
                    "meeting_id": meeting_uuid,
                    "response_text": response_text,
                    "response_type": response_type,
                    "trigger": trigger,
                    "related_fact_ids": json.dumps(related_fact_ids or []),
                    "related_assumption_ids": json.dumps(related_assumption_ids or []),
                    "related_action_ids": json.dumps(related_action_ids or []),
                    "approval_status": approval_status,
                    "approval_id": uuid.UUID(approval_id) if approval_id else None,
                    "execution_status": execution_status,
                    "jira_ticket_ref": jira_ticket_ref,
                    "confidence": confidence,
                    "created_at": now_utc,
                },
            )
            conn.commit()

        record = {
            "id": str(response_id),
            "meeting_id": meeting_id,
            "response_text": response_text,
            "response_type": response_type,
            "trigger": trigger,
            "related_fact_ids": related_fact_ids or [],
            "related_assumption_ids": related_assumption_ids or [],
            "related_action_ids": related_action_ids or [],
            "approval_status": approval_status,
            "approval_id": approval_id,
            "execution_status": execution_status,
            "jira_ticket_ref": jira_ticket_ref,
            "confidence": confidence,
            "created_at": now_utc.isoformat(),
        }

        # Broadcast to WebSocket clients
        _broadcast_ai_response(meeting_id, record)

        logger.info(
            "[AI RESPONSE STORE] Stored %s response for meeting %s",
            response_type, meeting_id[:8],
        )
        return record

    except Exception as exc:
        logger.error("[AI RESPONSE STORE] Failed to store response: %s", exc)
        return None
    finally:
        engine.dispose()


def _broadcast_ai_response(meeting_id: str, record: dict[str, Any]) -> None:
    """Post ai_response_created event to backend internal broadcast endpoint."""
    import httpx

    backend_url = os.environ.get("BACKEND_INTERNAL_URL", "http://127.0.0.1:8000")
    url = f"{backend_url}/api/meetings/{meeting_id}/broadcast"
    payload = {
        "type": "ai_response_created",
        "meeting_id": meeting_id,
        "ai_response": record,
    }
    try:
        httpx.post(url, json=payload, timeout=2.0)
    except Exception as exc:
        logger.debug("[AI RESPONSE STORE] Broadcast failed (normal if offline): %s", exc)
